<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'matthieumastadenis\\couleur\\' => array($vendorDir . '/matthieumastadenis/couleur/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\VarDumper\\' => array($vendorDir . '/symfony/var-dumper'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'Michelf\\' => array($vendorDir . '/michelf/php-markdown/Michelf'),
    'Deljdlx\\WPTaverne\\' => array($baseDir . '/src/class'),
);
