<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit516aa046234963da149b0467682acfce
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'd6827b35d35e6c9602a5210955a293b7' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/utils.php',
        '22ec25e297fb2b306362a6648903e129' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/css/conversions.php',
        '8de1da307966be5c44353a9c1af7ffb4' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/css/utils.php',
        'f961a28a70e91fcb90dc8d15e88c99f8' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hexRgb/conversions.php',
        'e9358fe90b14f5430e5e8cee2de02b05' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hexRgb/utils.php',
        '7e4d8eb0e1726bf003614d4e1bfd463f' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hsl/conversions.php',
        '8f13a3beae846725dadb2d93b4fdfc17' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hsl/utils.php',
        '0e13dbfedd96ae5a6076f0ea917ce0a6' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hsv/conversions.php',
        'b12a36bd39be8f5aeab341a99b94b5b9' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hsv/utils.php',
        '9fed59bdeb6a9fd488d3824114010f1d' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hwb/conversions.php',
        '1eb2953d18dc58307230f9bdef62ce5b' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/hwb/utils.php',
        '67075e19fb31ab1404dfa0da2bb4231a' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/lab/conversions.php',
        '9e428a3a7a31ee00e4f9869d14b0a036' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/lab/utils.php',
        '195424b7ed1af4d8a50cddbf81c2e2c8' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/lch/conversions.php',
        '64220cd56bb95ecdbf5b9047386f2b76' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/lch/utils.php',
        'd7a29f44e13c2431e2bb87e262e71be7' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/linP3/conversions.php',
        '31ba89f8618e7fcc08fe2caad9b47886' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/linP3/utils.php',
        '358e679fba9747db109b34fff05d849b' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/linProPhoto/conversions.php',
        'dd65a3c61a5b3eb9b5ca8af2ca532e87' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/linProPhoto/utils.php',
        '324976a6180f2efa8a08f473c9bf1aee' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/linRgb/conversions.php',
        'a7136e0477452bf629e9b1c677ef4eb7' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/linRgb/utils.php',
        '4895da6d6c3d18dc71505c147511be2d' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/okLab/conversions.php',
        '6f4a4f592b636ae9760caa3f48991ad0' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/okLab/utils.php',
        'fc886e50ae347173bb177d25e5c71586' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/okLch/conversions.php',
        '792c9ef3144f419b8956c3f1495f150d' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/okLch/utils.php',
        'dab50859fcd33886693aca7f48e9cac4' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/p3/conversions.php',
        'cd06af80148482320164b291d9576754' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/p3/utils.php',
        '456203e1b0d7bdcd0472595324d7fb2b' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/proPhoto/conversions.php',
        'd8cd295d4ff36ba6873e9ca5312e9a8d' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/proPhoto/utils.php',
        'd797a1f72e63c0bad0bf39639d6d907d' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/rgb/conversions.php',
        'a3df7df2860cecc9de6e48a66efcd0d6' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/rgb/utils.php',
        'fcaaf6d909c5091f6109e3a13eecf02f' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/xyzD50/conversions.php',
        '46855b1fce55ccfe12513fa05b3d53bb' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/xyzD50/utils.php',
        'ad08779616ed7c415fcc8703ec1bdc7f' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/xyzD65/conversions.php',
        '8fe8468ad95f1366b7a99c72cebc8e60' => __DIR__ . '/..' . '/matthieumastadenis/couleur/src/utils/xyzD65/utils.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
    );

    public static $prefixLengthsPsr4 = array (
        'm' => 
        array (
            'matthieumastadenis\\couleur\\' => 27,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\VarDumper\\' => 28,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'M' => 
        array (
            'Michelf\\' => 8,
        ),
        'D' => 
        array (
            'Deljdlx\\WPTaverne\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'matthieumastadenis\\couleur\\' => 
        array (
            0 => __DIR__ . '/..' . '/matthieumastadenis/couleur/src',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\VarDumper\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-dumper',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Michelf\\' => 
        array (
            0 => __DIR__ . '/..' . '/michelf/php-markdown/Michelf',
        ),
        'Deljdlx\\WPTaverne\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/class',
        ),
    );

    public static $prefixesPsr0 = array (
        'A' => 
        array (
            'Analog' => 
            array (
                0 => __DIR__ . '/..' . '/analog/analog/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit516aa046234963da149b0467682acfce::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit516aa046234963da149b0467682acfce::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit516aa046234963da149b0467682acfce::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit516aa046234963da149b0467682acfce::$classMap;

        }, null, ClassLoader::class);
    }
}
