<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'matthieumastadenis\\couleur\\' => array($vendorDir . '/matthieumastadenis/couleur/src'),
    'Michelf\\' => array($vendorDir . '/michelf/php-markdown/Michelf'),
    'Deljdlx\\WPTaverne\\' => array($baseDir . '/src/class'),
);
