<?php return array(
    'root' => array(
        'name' => 'jdlxt/wptaverne',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '4bc52f994c6cdbbb1e81412f7232c6fddc91019b',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'jdlxt/wptaverne' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '4bc52f994c6cdbbb1e81412f7232c6fddc91019b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthieumastadenis/couleur' => array(
            'pretty_version' => 'v0.1.2',
            'version' => '0.1.2.0',
            'reference' => '3842cf51c9517e77afaa0a36ec78643a0c258e0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthieumastadenis/couleur',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'michelf/php-markdown' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'eb176f173fbac58a045aff78e55f833264b34e71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../michelf/php-markdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
